### PR TITLE
Add control space after i.e. and e.g.

### PR DESCRIPTION
**Pull request by migueldvb**

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
actually, I believe these `\` should be replaced with commas, for grammatical correctness.

**Comment by migueldvb** [comment]
that's a good suggestion.

**Comment by kyleniemeyer** [comment]
If you want to convert those `\` to `,`, I'll merge it—otherwise I can make the changes instead and close the pull request

**Comment by migueldvb** [comment]
OK thanks, I will change the \ to , in this branch.

**Pull request merged**
